### ISSUE TITLE
Clicking to select Stroke or Fill sets the R G and B values incorrectly

### ISSUE THREAD

**Issue by salmelo** [operation404/boneyard-drawing-tools#6]
For example, this is what it looks like after I click the fill button.
![image](https://github.com/operation404/boneyard-drawing-tools/assets/1094329/122cdeff-e247-45c6-9b8e-126bfbe79aa2)

**Comment by operation404** [comment]
Do you have more information about this behavior? Things like foundry version, whether this happens with other modules enabled, or any console errors? Unfortunately without more details it's proving difficult to replicate.

**Comment by salmelo** [comment]
it's stopped doing it to me now as well. The only thing I can think of is I had just installed and enabled it, maybe something to do with that. I'm on 11.315. If it crops up again I'll be sure to look for more details.

**Comment by operation404** [comment]
Glad to hear it's gone away, possibly some issue with failing to get the saved colors before rendering the UI. Let me know if it comes up again.
